version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"     
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/common"   
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/proxy"  
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/paper" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/tools" 
    schedule:
      interval: "weekly"
